name: Lint and test
on:
  push:
    branches:
      - develop
  pull_request:
jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y -qq build-essential git sqlite libtag1-dev ffmpeg mpv zlib1g-dev
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.x
          cache: false
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: "--timeout=5m"
